packages:
  - "packages/*"
  - "apps/playground"
  - "apps/docs"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - better-sqlite3
  - sharp

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver
  - vue-demi
